Sylius\Component\User\Model\User:
    exclusion_policy: ALL
    xml_root_name: sylius_user
    properties:
        id:
            expose: true
            type: integer
            groups: [FormData] #Default, Detailed, DetailedCart
        username:
            expose: true
            type: string
            groups: [Default, Detailed, DetailedCart, Secured]
        usernameCanonical:
            expose: true
            type: string
            groups: [Detailed, DetailedCart]
        email:
            expose: true
            type: string
            groups: [Default, Detailed, DetailedCart]
        emailCanonical:
            expose: true
            type: string
            groups: [Detailed, DetailedCart]
        enabled:
            expose: true
            type: boolean
            groups: [Default, Detailed]
        roles:
            expose: false
#            type: array
#            groups: [Detailed]
